# Terraform Pipeline for Windows

# trigger:

trigger:

- tgs-dev



pool:

  vmImage: 'windows-latest'



steps:



- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0

  displayName: Install Terraform

  inputs:

     terraformVersion: '0.14.5'

 

- bash: sed -i 's/backend "gcs"/backend "local"/g' main.tf

  workingDirectory: $(Build.Repository.LocalPath)

  displayName: update to local backend




- bash: terraform init

  workingDirectory: $(Build.Repository.LocalPath)

  displayName: terraform init GCP-TGS-infra-SW




- bash: sed -i 's/backend "local"/backend "gcs"/g' main.tf

  workingDirectory: $(Build.Repository.LocalPath)

  displayName: update back to gcs backend



- bash: rm -rf $(Build.Repository.LocalPath)/.terraform

  displayName: remove terraform plugin cache




- task: PublishBuildArtifacts@1

  inputs:

    pathtoPublish: '$(Build.Repository.LocalPath)'

    artifactName: drop